# Generated by Django 6.0.1 on 2026-01-13 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctorApp', '0001_initial'),
        ('pacienteApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='reservas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion_dolor', models.CharField(max_length=500)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('estado', models.CharField(default='pendiente', max_length=20)),
                ('nombre_paciente', models.CharField(max_length=40)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas_asignadas', to='doctorApp.doctor')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mis_reservas', to='pacienteApp.paciente')),
            ],
        ),
    ]
